### ISSUE TITLE
Chrome Web Browser Incompatibility

### ISSUE THREAD

**Issue by starpebble** [aws-samples/aws-mobile-appsync-chat-starter-angular#24]
On Chrome, there is an error.

I tried the app in Firefox and Safari, and two users can chat.  There are no errors in the web browser console.

How can I fix the demo to work in Chrome?

Preceding log statements:
```
getAllUsers - Got data Array(1)
webpack-internal:///./src/app/chat-app/chat-convo-list/chat-convo-list.component.ts:46 Fetched convos data undefined
webpack-internal:///./src/app/chat-app/chat-convo-list/chat-convo-list.component.ts:48 getUserConversationsConnection: no data
```

The log statement indicating an error in Chrome:
```json
webpack-internal:///./node_modules/aws-appsync/node_modules/apollo-client/core/ObservableQuery.js:296 Unhandled error Network error: Can't find field conversations({"first":10}) on object (User:1ae7332b-817b-4a2d-9575-8fe96d47834a) {
  "__typename": "User",
  "id": "1ae7332b-817b-4a2d-9575-8fe96d47834a",
  "cognitoId": "1ae7332b-817b-4a2d-9575-8fe96d47834a",
  "username": "person098",
  "registered": false
}. Error: Network error: Can't find field conversations({"first":10}) on object (User:1ae7332b-817b-4a2d-9575-8fe96d47834a) {
  "__typename": "User",
  "id": "1ae7332b-817b-4a2d-9575-8fe96d47834a",
  "cognitoId": "1ae7332b-817b-4a2d-9575-8fe96d47834a",
  "username": "person098",
  "registered": false
}.
    at new ApolloError (webpack-internal:///./node_modules/aws-appsync/node_modules/apollo-client/errors/ApolloError.js:36:28)
    at eval (webpack-internal:///./node_modules/aws-appsync/node_modules/apollo-client/core/QueryManager.js:287:41)
    at eval (webpack-internal:///./node_modules/aws-appsync/node_modules/apollo-client/core/QueryManager.js:668:17)
    at Array.forEach (<anonymous>)
    at eval (webpack-internal:///./node_modules/aws-appsync/node_modules/apollo-client/core/QueryManager.js:667:18)
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (webpack-internal:///./node_modules/aws-appsync/node_modules/apollo-client/core/QueryManager.js:662:22)
    at eval (webpack-internal:///./node_modules/aws-appsync/node_modules/apollo-client/core/QueryManager.js:236:31)
    at ZoneDelegate.invoke (webpack-internal:///./node_modules/zone.js/dist/zone.js:388:26)
    at Object.onInvoke (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4965:33)
```

I am evaluating app sync for use.  This demo chat web app is impaired in the Chrome web browser.  A user does not receive messages in real time.  Probably because of this error.  On Firefox and Safari, the chat room sends and receives messages in real time.  This implies graphql "subscriptions" are working on Firefox and Safari.  What's wrong with the web application javascript in the Chrome Web Browser?

My device:
Platform: Mac OS X 10.13.6
Browser: Chrome Version 70.0.3528.4

**Comment by starpebble** [comment]
@awsed Can you help me find someone to work with to resolve this issue?

**Comment by awsed** [comment]
Tested on Chrome Version 67.0.3396.99 (Official Build) (64-bit) with different users as well as using incognito mode. Works fine, cannot replicate.

You are using chrome from the dev channel. Suggest to use the stable channel.
