### ISSUE TITLE
Unable to display registered users under ChatQL users list

### ISSUE THREAD

**Issue by cloudDev12** [aws-samples/aws-mobile-appsync-chat-starter-angular#26]
Hi, I am rather new to React/GraphQL and thought to follow along with this simple tutorial example. 
I have managed to get it working now (thanks to those who helped) however I am unable to see the list of users I have created under the user list. I have made over 3 of them yet nothing shows up.
Upon further investigation, in the users table generate as part of the sample code is empty and none of the users I've created show up there. 
Could someone please suggest what my be going wrong?
Thanks in advance!
![no users](https://user-images.githubusercontent.com/35764220/44655511-b8326100-aa38-11e8-8f6e-1a3a912a4d67.PNG)

**Comment by awsed** [comment]
Do you get any errors in the browser developer console? If so, we need them to help troubleshoot.

**Comment by awsed** [comment]
Closing due to inactivity

**Comment by cloudDev12** [comment]
Sorry for the inactivity i have been very unwell and haven't been able to provide more info. Please re-open. Will give more info tomorrow when im back at my laptop

**Comment by cloudDev12** [comment]
From memory i e registered multiple users but i didnt get any errors and nothing gets added to dynamodb.

**Comment by cloudDev12** [comment]
Hi @awsed , below is the error log from the browser developer console. 
Any suggestions on what could be going wrong?

`Failed to load resource: the server responded with a status of 500 ()
ObservableQuery.js:289 Unhandled error Network error: Response not successful: Received status code 500 Error: Network error: Response not successful: Received status code 500
    at new ApolloError (http://localhost:4200/vendor.js:117382:28)
    at http://localhost:4200/vendor.js:116429:41
    at http://localhost:4200/vendor.js:116810:17
    at Array.forEach (<anonymous>)
    at http://localhost:4200/vendor.js:116809:18
    at Map.forEach (<anonymous>)
    at QueryManager.push../node_modules/aws-appsync/node_modules/apollo-client/core/QueryManager.js.QueryManager.broadcastQueries (http://localhost:4200/vendor.js:116804:22)
    at http://localhost:4200/vendor.js:116378:31
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.js:10967:26)
    at Object.onInvoke (http://localhost:4200/vendor.js:47138:33)
observer._subscription._observer.error @ ObservableQuery.js:289
yvpbkdaorzcwrdwuau6m25csny.appsync-api.ap-southeast-2.amazonaws.com/graphql:1 Failed to load resource: the server responded with a status of 500 ()
send.js:80 TypeError: Cannot read property 'find' of undefined
    at Object.discard (offline-link.js:213)
    at _callee$ (send.js:69)
    at tryCatch (runtime.js:62)
    at Generator.invoke [as _invoke] (runtime.js:296)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:4200/vendor.js:204395:21)
    at step (asyncToGenerator.js:17)
    at asyncToGenerator.js:35
    at new Promise (es6.promise.js:164)
    at asyncToGenerator.js:14
    at send.js:109
_callee$ @ send.js:80
es6.promise.js:97 Unhandled promise rejection Error: Network error: Response not successful: Received status code 500
    at new ApolloError (ApolloError.js:34)
    at Object.error (QueryManager.js:118)
    at SubscriptionObserver.error (zen-observable.js:178)
    at SubscriptionObserver.error (zen-observable.js:178)
    at SubscriptionObserver.error (zen-observable.js:178)
    at SubscriptionObserver.error (zen-observable.js:178)
    at httpLink.js:88
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:388)
    at Object.onInvoke (core.js:4749)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:387)`

**Comment by awsed** [comment]
If you go to the network tab, there should be a response with a more descriptive error. Can you check?

It might not be the problem but recently my project went out of sync for some reason and the Mobile CLI created a new Cognito User Pool however AppSync was still pointing to the old user pool. Please confirm in the AppSync Conole, the Cognito User Pools details match the identifier in teh aws_exports.js file. Also confirm you can authenticate from the AppSync Console to the User Pools in the Query section.

**Comment by cloudDev12** [comment]
Hi @awsed thanks for your reply. Ive taken a screenshot attached. 
![network tab errors](https://user-images.githubusercontent.com/35764220/45296570-c9ee2b00-b545-11e8-9564-9c8be1f47425.PNG)

Also upon looking at the AppSync, it was created in Sydney region, however for some reason my buckets were created in US-EAST-1. See below
`'aws_cognito_identity_pool_id': 'us-east-1:xxxxx',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'xxxxx',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'xxxxx',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': 'xxxxx',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'xxxxx',
    'aws_project_name': 'xxxxx',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'xxxx',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_xxxx',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': 'xxxxx',`

How could I correct this? Just create a new AppSync project, re-download the schema/repo?

**Comment by awsed** [comment]
Suggest the best way is start from scratch following the instructions after configuring the Mobile CLI for the correct region.
