### ISSUE TITLE
Schema validation failed with the following errors:

### ISSUE THREAD

**Issue by astro21** [aws-samples/aws-mobile-appsync-chat-starter-angular#50]
Node version v8.11.1

I followed the same steps and got the following error when running " ng serve" and "amplify serve".

Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/Users/username/Work/appsync/aws-mobile-appsync-chat-starter-angular/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)
    at MergeMapSubscriber._tryNext (/Users/username/Work/appsync/aws-mobile-appsync-chat-starter-angular/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/username/Work/appsync/aws-mobile-appsync-chat-starter-angular/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/username/Work/appsync/aws-mobile-appsync-chat-starter-angular/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/Users/username/Work/appsync/aws-mobile-appsync-chat-starter-angular/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/Users/username/Work/appsync/aws-mobile-appsync-chat-starter-angular/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/Users/username/Work/appsync/aws-mobile-appsync-chat-starter-angular/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/Users/username/Work/appsync/aws-mobile-appsync-chat-starter-angular/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/Users/username/Work/appsync/aws-mobile-appsync-chat-starter-angular/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/Users/username/Work/appsync/aws-mobile-appsync-chat-starter-angular/node_modules/rxjs/internal/operators/switchMap.js:86:26)

frontend start command exited with code 1

**Comment by awsed** [comment]
What version of the CLI are you using? I could not replicate with the latest version:

```
amplify version
Scanning for plugins...
Plugin scan successful
3.9.0
```
