### ISSUE TITLE
getting error on awsmobile run

### ISSUE THREAD

**Issue by allanspear** [aws-samples/aws-mobile-appsync-chat-starter-angular#7]
I am getting error when trying to start the application.

```
webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
    at Object.get [as CommonsChunkPlugin] (/root/aws-mobile-appsync-chat-starter-angular/node_modules/webpack/lib/webpack.js:162:10)
    at Object.getBrowserConfig (/root/aws-mobile-appsync-chat-starter-angular/node_modules/@angular/cli/models/webpack-configs/browser.js:27:48)
    at NgCliWebpackConfig.buildConfig (/root/aws-mobile-appsync-chat-starter-angular/node_modules/@angular/cli/models/webpack-config.js:31:77)
    at Class.run (/root/aws-mobile-appsync-chat-starter-angular/node_modules/@angular/cli/tasks/serve.js:71:98)
    at check_port_1.checkPort.then.port (/root/aws-mobile-appsync-chat-starter-angular/node_modules/@angular/cli/commands/serve.js:123:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

```

**Comment by onlybakam** [comment]
you are most likely using a newer version of `immutability-helper`.
in your source directory can you try:
`npm install --save --save-exact immutability-helper@2.6.0`

then try running `awsmobile run` again

**Comment by onlybakam** [comment]
closing due to inactivity
